# Lecture 4: 28.08.24

### NAMING CONVENTION IN PYTHON

### 1.Snake Case

In snake case, each word in a variable is seperated by underscores

In [5]:
user_name="Kumkum"
my_marks=90

#creating function with snake case#creati
def calculate_avg(list):
    total = sum(list)
    return total/len(list)
    
average =calculate_avg([10,20,30])
print(average)

20.0


### 2. Camel Case

In camel case,Each word except the first, starts with a capital letter.

In [6]:
#creating variables with camel case
userName ="Kumkum"
myMarks = 90

### 3.Pascal Case

In Pascal case, each word starts with the capital letter

In [15]:
#creating variable with pascal case

MyName = "Kumkum"


### 4.Uppercase with underscores

In uppercase with underscores, each word is of uppercase seperated by undescores

In [19]:
MY_NAME = "Kumkum Malhotra"

#constant names 

PI = 3.14
def volumeOfCylinder(radius, height):
    volume = PI*radius*radius*height
    return volume

print(volumeOfCylinder(2, 6))

75.36


In [20]:
#a user has 3X3 and then in the copied matrix multilpy each value by a constant and store the value in place
#after this print both the matrix
import numpy as np

original_matrix = np.array([
    [11,22,33],
    [44,55,66],
    [77,88,99]
])

constant =10
modified_matrix = original_matrix*constant

print("Original matrix: ",original_matrix)
print("Modified matrix: ",modified_matrix)

Original matrix:  [[11 22 33]
 [44 55 66]
 [77 88 99]]
Modified matrix:  [[110 220 330]
 [440 550 660]
 [770 880 990]]
